# makefile
#
# Created on: 16 Jun 2014
#     Author: bone
#


OUTPUT = portaudio-product.out

SOURCES = bone-main.c

LIBRARIES = -lportaudio

FLAGS = -Wall -pedantic

all:
	gcc -o ${OUTPUT} ${SOURCES} ${LIBRARIES}
	